export default {
  PAUSE: require('../assets/pause.png'),
  START: require('../assets/start.png'),
  KAKAO: require('../assets/kakao.png'),
  GRAPECIRCLE: require('../assets/grape_circle.png'),
  GRAPEFORCONFETTI: require('../assets/grape_confetti.png'),
  LOGO: require('../assets/logo.gif'),
  BOX: require('../assets/boxBlack.png'),
  BOX_SMALL: require('../assets/boxBlack_small.png'),
  CHEVRON: require('../assets/chevron.png'),
  ARROW: require('../assets/arrow.png'),
  EMOTION: {
    ANGRY: require('../assets/emotion/ANGRY.png'),
    EXCITED: require('../assets/emotion/EXCITED.png'),
    GLOOMY: require('../assets/emotion/GLOOMY.png'),
    HAPPY: require('../assets/emotion/HAPPY.png'),
    IRRITATED: require('../assets/emotion/IRRITATED.png'),
    LETHARGIC: require('../assets/emotion/LETHARGIC.png'),
    PLEASED: require('../assets/emotion/PLEASED.png'),
    PROUD: require('../assets/emotion/PROUD.png'),
    UNSTABLE: require('../assets/emotion/UNSTABLE.png'),
  },
  GRAPES: [
    require(`../assets/grapes/1.png`),
    require(`../assets/grapes/2.png`),
    require(`../assets/grapes/3.png`),
    require(`../assets/grapes/4.png`),
    require(`../assets/grapes/5.png`),
    require(`../assets/grapes/6.png`),
    require(`../assets/grapes/7.png`),
    require(`../assets/grapes/8.png`),
    require(`../assets/grapes/9.png`),
    require(`../assets/grapes/10.png`),
  ],
}

// console.log(...Array.from({ length: 10 }, (_, i) => i))
