export default {
  PAUSE: require('../assets/pause.png'),
  START: require('../assets/start.png'),
  KAKAO: require('../assets/kakao.png'),
  GRAPECIRCLE: require('../assets/grape_circle.png'),
  GRAPEFORCONFETTI: require('../assets/grape_confetti.png'),
  LOGO: require('../assets/logo.gif'),
  BOX: require('../assets/boxBlack.png'),
  BOX_SMALL: require('../assets/boxBlack_small.png'),
  CHEVRON: require('../assets/chevron.png'),
  EMOTION: {
    ANGRY: require('../assets/emotion/ANGRY.png'),
    EXCITED: require('../assets/emotion/EXCITED.png'),
    GLOOMY: require('../assets/emotion/GLOOMY.png'),
    HAPPY: require('../assets/emotion/HAPPY.png'),
    IRRITATED: require('../assets/emotion/IRRITATED.png'),
    LETHARGIC: require('../assets/emotion/LETHARGIC.png'),
    PLEASED: require('../assets/emotion/PLEASED.png'),
    PROUD: require('../assets/emotion/PROUD.png'),
    UNSTABLE: require('../assets/emotion/UNSTABLE.png'),
  },
}
