export default {
  LOGO: require('../assets/ggobuk.png'),
  LOGO_MOVING: require('../assets/moving_ggobuk.gif'),
  GRAPE: require('../assets/grape.png'),
  WATCH: require('../assets/apple_watch.png'),
  HEART: require('../assets/heart.png'),
  WATCH_PREV: require('../assets/watch_prev.png'),
  WATCH_APP: require('../assets/watch_app.png'),
  WATCH_HEART: require('../assets/apple_watch_heart.png'),
  SENDBOX_BLACK: require('../assets/sendbox_black.png'),
  FOLD: require('../assets/fold.png'),
  UNFOLD: require('../assets/unfold.png'),
  NEXTSTORY: require('../assets/nextStory.png'),
  INTERSECT: require('../assets/Intersect.png'),
  TREE: require('../assets/tree.png'),
  GRAPEBOX: require('../assets/grapeBox.png'),
  PAUSETURTLE: require('../assets/pauseTurtle.png'),
  ATTENTIONTURTLE: require('../assets/attentionTurtle.png'),
  GRAPEFULL: require('../assets/grapeFull.png'),
}
